version: '3'
services:
  server:
    build: ./server
    image: mmbese/cc_ex3:server
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-service
      - product-descp-service
      - product-price-service
  hello-world-service:
    build: ./hello-world-service
    image: mmbese/cc_ex3:hello-world-service
  product-descp-service:
    build: ./product-descp-service
    image: mmbese/cc_ex3:product-descp-service
  product-price-service:
    build: ./product-price-service
    image: mmbese/cc_ex3:product-price-service

